version: '3.8'

services:
  web:
    container_name: api
    build: .
    env_file:
      - .env.local
    ports:
      - 3000:3000
    depends_on:
    - db
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: